<?php
// This file generated by Propel 1.6.7 convert-conf target
// from XML runtime conf file /var/www/centraldeadoradores/application/configs/propel/runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'centraldeadoradores' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'settings' => 
        array (
          'charset' => 
          array (
            'value' => 'utf8',
          ),
        ),
        'dsn' => 'mysql:host=localhost;dbname=adoradores',
        'user' => 'root',
        'password' => 'supermario',
      ),
    ),
    'default' => 'centraldeadoradores',
  ),
  'generator_version' => '1.6.7',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-centraldeadoradores-conf.php');
return $conf;