<script type="text/javascript">
	var toSend = [];
	$(document).ready(function(){
		var destinatarios = [];
		$("#envioemailform").submit(function(){
			var oEditor = CKEDITOR.instances.corpoMensagem;
			if($(toSend).size() === 0){
				$.ajax({
					url: '/ajax/geterroralert',
					type: 'post',
					dataType: 'html',
					data: {"texto":"Por favor, escolha pelo menos 1 destinatário válido!"},
					success: function(data) {
						$("#alerts").html(data);
						$(document).scrollTop(0);
					}
				});
				return false;
			} else if($("#assunto").val() == ""){
				$.ajax({
					url: '/ajax/geterroralert',
					type: 'post',
					dataType: 'html',
					data: {"texto":"Por favor, digite o assunto!"},
					success: function(data) {
						$("#alerts").html(data);
						$(document).scrollTop(0);
					}
				});
				return false;
			} else if(oEditor.getData() == ""){
				$.ajax({
					url: '/ajax/geterroralert',
					type: 'post',
					dataType: 'html',
					data: {"texto":"Por favor, digite o conteúdo do e-mail!"},
					success: function(data) {
						$("#alerts").html(data);
						$(document).scrollTop(0);
					}
				});
				return false;
			} else {
				//Marcar mensagem para envio
				$("#destinatario").prop('disabled', true);
				$("#assunto").prop('disabled', true);
				oEditor.setReadOnly(true);
				$("#enviar").button('loading');	
				jQuery.each(toSend, function(i, val) {
					$("#envioemailform").append("<input type='hidden' id='destinatarios[]' name='destinatarios[]' value='" + val + "' />");
				});
			}
		});
		$("#destinatario").after("<div id='selecionados'></div>");
		$.ajax({
			url: '/ajax/getdestinatarios',
			dataType: 'json',
			success: function(data) {
				
				jQuery.each(data, function(i, val) {
					destinatarios.push(val.Nome);
				});
				$("#destinatario").typeahead({
					source:destinatarios,
				    onselect: function (obj) {
				        adicionarDestinatario($("#destinatario"));
				    }
				});
			}
		});
		
		$("#destinatario").focus(function(){
			$(this).keypress(function(event) {
				if ( event.which == 13 && jQuery.inArray($(this).val(), destinatarios) != -1) {
					adicionarDestinatario($(this));
					event.preventDefault();
				}
			});
		});
		if(verifyBrowser()){
			$("#arquivo").change(function(){
				var arquivo = document.getElementById('arquivo');
				if(arquivo.files[0].size > 8000000){
					$.ajax({
						url: '/ajax/geterroralert',
						type: 'post',
						dataType: 'html',
						data: {"texto":"O arquivo para upload deve ser menor que 8MB."},
						success: function(data) {
							$("#alerts").html(data);
						}
					});
				}
				else{
					$("#alerts").html("");
				}
			});
		} else {
						
		}
	});
	function adicionarDestinatario(destinatario){
		if(jQuery.inArray($(destinatario).val(), toSend) == -1){
			var arr = $(destinatario).val().split(':');
			var type = "";
			if(arr[0] == "Banda"){
				type = "Banda";
			} else if(arr[0] == "Area"){
				type = "Area";
			} else if(arr[0] == "Função"){
				type = "Funcao";
			} else if(arr[0] == "Todos"){
				type = "Todos";
				toSend = [];
				$("#selecionados").html('');
				$("#destinatario").prop('disabled', true);
			} else {
				type = "Usuario";
			}
			$("#selecionados").append("<div title='"+$(destinatario).val()+"' class='dest dest" + type + "'>"+$(destinatario).val()+"<span class='close' style='margin-left:3px;' onclick='removeDest($(this).parent())'>×</span></div>");
			toSend.push($(destinatario).val());
		}
		$(destinatario).val("");
	}
	function removeDest(comp){
		toSend = jQuery.grep(toSend, function(value) {
			  return value != $(comp).attr("title");
		});
		if($(comp).attr('title') == "Todos"){
			$("#destinatario").prop('disabled', false);
		}
		$(comp).remove();
	}
</script>
<div id="teste"></div>
<h3>Enviar E-mail</h3>
<form id="envioemailform" method="post" action="/envioemail/marcarenvio" enctype="multipart/form-data">
	<div class="form-inline">
		<div class="control-group" >
			<span class="help-block">Digite o nome dos usuários que serão os destinatários do e-mail ou 'Banda' para escolher uma Banda,
			ou 'Ministério' para escolher um ministério, ou 'Função' para escolher uma função. Quando encontrar o destinatário que
			deseja, aperte enter.</span>
			<label class="control-label" for="destinatario" class="input-xxlarge">Destinatários: </label>
			<input id="destinatario" type="text">
		</div>
		<div class="control-group" >
			<label class="control-label" for="assunto">Assunto: </label>
			<input type="text" name="assunto">
		</div>
		<div class="control-group">
		    <label class="control-label" for="arquivo">Anexo :</label>
			<input class="span5" type="file" id="arquivo" name="arquivo" />
			<span class="help-block" style="color:red;">Por favor, por enquanto só use o anexo para testes. Esta funcionalidade esta em "BETA".</span>
		</div>
		<div class="control-group" >
			<label class="control-label" for="assunto">Mensagem: </label>
			<textarea class="ckeditor" id="corpoMensagem" name="corpoMensagem"></textarea>
		</div>
		<div class="form-actions">
			<button id="enviar" class="btn btn-primary pull-right" autocomplete="off" data-loading-text="Enviando..." >Enviar</button>
		</div>
	</div>
</form>